In [2]:
#r "nuget: Deedle.Interactive"
#r "nuget: FsHttp"

Loading extensions from `C:\Users\schne\.nuget\packages\deedle.interactive\3.0.0\lib\netstandard2.1\Deedle.Interactive.dll`

In [3]:
open Deedle

let df = Frame.ReadCsv("./ProjectsWithTotalAttributes.csv")
df

0,->,PRJNA852208,10533
1,->,PRJEB15671,8315
2,->,PRJEB25079,6986
3,->,PRJNA945404,6909
4,->,PRJEB19252,4882
:,,...,...
821,->,PRJNA319661,22
822,->,PRJNA718567,18
823,->,PRJNA117657,18
824,->,PRJNA744531,16
825,->,PRJNA79813,15

In [4]:
open FsHttp
open System.Xml.Linq

let getAlias acc = 
    http {
        GET $"https://www.ebi.ac.uk/ena/browser/api/xml/{acc}"
    }
    |> Request.send
    |> Response.toText
    |> XDocument.Parse
    |> fun doc -> doc.Descendants(XName.Get "SECONDARY_ID")
    |> Seq.map (fun e -> e.Value)
    |> String.concat ";"

In [5]:
let mapped_df =
    df
    |> fun f ->
        let alias_col =
            f
            |> Frame.mapRows (fun rk os ->
                let acc = os.GetAs<string>("Project_Accession")
                printfn "getting alias for %s" acc
                getAlias acc
            )
        f
        |> Frame.addCol "Alias" alias_col

getting alias for PRJNA852208
getting alias for PRJEB15671
getting alias for PRJEB25079
getting alias for PRJNA945404
getting alias for PRJEB19252
getting alias for PRJNA236110
getting alias for PRJNA808745
getting alias for PRJNA368916
getting alias for PRJNA358059
getting alias for PRJNA666631
getting alias for PRJNA475542
getting alias for PRJNA817215
getting alias for PRJNA989636
getting alias for PRJNA915364
getting alias for PRJNA504621
getting alias for PRJNA483458
getting alias for PRJNA302221
getting alias for PRJNA770533
getting alias for PRJNA515610
getting alias for PRJNA611770
getting alias for PRJNA638728
getting alias for PRJNA841954
getting alias for PRJNA663790
getting alias for PRJNA900135
getting alias for PRJNA779072
getting alias for PRJNA382136
getting alias for PRJNA615216
getting alias for PRJNA224705
getting alias for PRJNA551415
getting alias for PRJNA378644
getting alias for PRJNA689309
getting alias for PRJNA727531
getting alias for PRJNA871888
getting alias for PRJNA545612
getting alias for PRJNA792010
getting alias for PRJNA691022
getting alias for PRJNA419306
getting alias for PRJNA641096
getting alias for PRJNA429659
getting alias for PRJNA481720
getting alias for PRJNA730903
getting alias for PRJNA1014093
getting alias for PRJNA874688
getting alias for PRJNA737113
getting alias for PRJNA493616
getting alias for PRJNA938512
getting alias for PRJNA566089
getting alias for PRJNA544417
getting alias for PRJNA478998
getting alias for PRJNA630258
getting alias for PRJNA575019
getting alias for PRJNA628644
getting alias for PRJNA625566
getting alias for PRJNA497989
getting alias for PRJNA612487
getting alias for PRJNA311764
getting alias for PRJNA506000
getting alias for PRJNA477936
getting alias for PRJNA745095
getting alias for PRJNA287627
getting alias for PRJNA545832
getting alias for PRJNA588176
getting alias for PRJNA916484
getting alias for PRJNA318880
getting alias for PRJNA695076
getting alias for PRJNA639173
getting alias for PRJNA1096312
getting alias for PRJNA560779
getting alias for PRJNA636648
getting alias for PRJNA476754
getting alias for PRJNA1020877
getting alias for PRJNA513321
getting alias for PRJNA525997
getting alias for PRJNA549850
getting alias for PRJNA534240
getting alias for PRJNA622644
getting alias for PRJNA649955
getting alias for PRJNA602947
getting alias for PRJNA705878
getting alias for PRJNA791625
getting alias for PRJNA672885
getting alias for PRJNA940403
getting alias for PRJNA613493
getting alias for PRJNA231088
getting alias for PRJNA677963
getting alias for PRJNA508267
getting alias for PRJNA991926
getting alias for PRJNA615658
getting alias for PRJNA601783
getting alias for PRJNA529391
getting alias for PRJEB33535
getting alias for PRJNA316697
getting alias for PRJNA665466
getting alias for PRJNA874053
getting alias for PRJNA662710
getting alias for PRJNA681862
getting alias for PRJNA660479
getting alias for PRJNA947662
getting alias for PRJNA222364
getting alias for PRJNA544694
getting alias for PRJNA808090
getting alias for PRJNA416120
getting alias for PRJNA377549
getting alias for PRJNA167620
getting alias for PRJNA977970
getting alias for PRJNA301684
getting alias for PRJNA1020153
getting alias for PRJNA715469
getting alias for PRJNA277424
getting alias for PRJNA912622
getting alias for PRJNA609342
getting alias for PRJNA640389
getting alias for PRJNA551115
getting alias for PRJNA981637
getting alias for PRJNA476778
getting alias for PRJNA716051
getting alias for PRJNA477359
getting alias for PRJNA641025
getting alias for PRJNA935771
getting alias for PRJNA511620
getting alias for PRJNA717313
getting alias for PRJNA362953
getting alias for PRJNA700573
getting alias for PRJNA716276
getting alias for PRJNA716659
getting alias for PRJNA661316
getting alias for PRJNA970811
getting alias for PRJNA642797
getting alias for PRJNA802649
getting alias for PRJNA818647
getting alias for PRJNA877346
getting alias for PRJNA169667
getting alias for PRJNA382583
getting alias for PRJNA427134
getting alias for PRJNA893217
getting alias for PRJNA811184
getting alias for PRJNA245920
getting alias for PRJNA767415
getting alias for PRJNA445300
getting alias for PRJNA369265
getting alias for PRJEB36508
getting alias for PRJNA725493
getting alias for PRJNA837279
getting alias for PRJNA855120
getting alias for PRJNA320769
getting alias for PRJNA806968
getting alias for PRJNA314105
getting alias for PRJNA934345
getting alias for PRJNA560053
getting alias for PRJNA473317
getting alias for PRJNA213000
getting alias for PRJNA837772
getting alias for PRJNA764922
getting alias for PRJNA406971
getting alias for PRJNA548919
getting alias for PRJNA434094
getting alias for PRJNA756203
getting alias for PRJNA716808
getting alias for PRJNA251351
getting alias for PRJNA831274
getting alias for PRJNA1013559
getting alias for PRJNA429247
getting alias for PRJNA868735
getting alias for PRJNA394661
getting alias for PRJNA433501
getting alias for PRJNA198192
getting alias for PRJNA554145
getting alias for PRJNA263595
getting alias for PRJNA613690
getting alias for PRJNA720907
getting alias for PRJNA595605
getting alias for PRJNA279505
getting alias for PRJNA359478
getting alias for PRJNA942274
getting alias for PRJNA521689
getting alias for PRJNA703036
getting alias for PRJNA721411
getting alias for PRJNA543989
getting alias for PRJNA513852
getting alias for PRJNA384359
getting alias for PRJNA216987
getting alias for PRJNA685167
getting alias for PRJNA300685
getting alias for PRJNA531168
getting alias for PRJNA790929
getting alias for PRJNA514040
getting alias for PRJNA901957
getting alias for PRJNA933126
getting alias for PRJNA842228
getting alias for PRJNA977810
getting alias for PRJNA601526
getting alias for PRJNA594026
getting alias for PRJNA688924
getting alias for PRJNA491484
getting alias for PRJNA624317
getting alias for PRJNA1025000
getting alias for PRJNA437500
getting alias for PRJNA792341
getting alias for PRJNA427432
getting alias for PRJNA554610
getting alias for PRJNA751488
getting alias for PRJNA312219
getting alias for PRJNA723009
getting alias for PRJNA681186
getting alias for PRJNA609240
getting alias for PRJNA435737
getting alias for PRJNA752148
getting alias for PRJNA746250
getting alias for PRJNA951436
getting alias for PRJNA765962
getting alias for PRJNA902769
getting alias for PRJNA723054
getting alias for PRJNA736396
getting alias for PRJNA916502
getting alias for PRJNA833078
getting alias for PRJNA847965
getting alias for PRJNA681183
getting alias for PRJNA629545
getting alias for PRJEB20931
getting alias for PRJNA279272
getting alias for PRJNA449619
getting alias for PRJNA522058
getting alias for PRJNA702173
getting alias for PRJNA975601
getting alias for PRJNA351870
getting alias for PRJNA529715
getting alias for PRJNA373836
getting alias for PRJNA753100
getting alias for PRJNA563055
getting alias for PRJNA717244
getting alias for PRJNA730562
getting alias for PRJNA415950
getting alias for PRJNA671859
getting alias for PRJNA646744
getting alias for PRJNA858805
getting alias for PRJNA667059
getting alias for PRJNA274887
getting alias for PRJNA1118315
getting alias for PRJNA271131
getting alias for PRJNA302602
getting alias for PRJNA827180
getting alias for PRJNA428240
getting alias for PRJNA844303
getting alias for PRJNA1079711
getting alias for PRJNA282742
getting alias for PRJNA231710
getting alias for PRJNA811774
getting alias for PRJNA485633
getting alias for PRJNA543995
getting alias for PRJNA481969
getting alias for PRJEB39363
getting alias for PRJNA779531
getting alias for PRJNA323943
getting alias for PRJNA945828
getting alias for PRJNA490087
getting alias for PRJNA645828
getting alias for PRJNA384185
getting alias for PRJNA888981
getting alias for PRJNA546251
getting alias for PRJNA390146
getting alias for PRJNA474441
getting alias for PRJNA326659
getting alias for PRJNA722743
getting alias for PRJNA593500
getting alias for PRJNA981151
getting alias for PRJNA369824
getting alias for PRJNA484219
getting alias for PRJNA595951
getting alias for PRJNA692443
getting alias for PRJNA388445
getting alias for PRJNA684322
getting alias for PRJNA484637
getting alias for PRJNA587704
getting alias for PRJNA649293
getting alias for PRJNA811122
getting alias for PRJNA807632
getting alias for PRJNA1035518
getting alias for PRJNA395664
getting alias for PRJNA846305
getting alias for PRJNA414399
getting alias for PRJNA707060
getting alias for PRJNA449910
getting alias for PRJNA832333
getting alias for PRJNA326408
getting alias for PRJNA308080
getting alias for PRJNA490893
getting alias for PRJNA287644
getting alias for PRJNA288783
getting alias for PRJNA323732
getting alias for PRJNA782298
getting alias for PRJNA933625
getting alias for PRJNA421355
getting alias for PRJNA511473
getting alias for PRJNA591466
getting alias for PRJNA471243
getting alias for PRJNA608657
getting alias for PRJNA762245
getting alias for PRJNA601157
getting alias for PRJNA609667
getting alias for PRJNA544565
getting alias for PRJNA978596
getting alias for PRJNA412106
getting alias for PRJNA597767
getting alias for PRJNA294703
getting alias for PRJNA890279
getting alias for PRJNA561790
getting alias for PRJNA379964
getting alias for PRJNA531668
getting alias for PRJNA532611
getting alias for PRJNA151239
getting alias for PRJNA1045678
getting alias for PRJNA736042
getting alias for PRJNA237959
getting alias for PRJNA524935
getting alias for PRJNA445392
getting alias for PRJNA858665
getting alias for PRJNA548174
getting alias for PRJNA899438
getting alias for PRJNA640823
getting alias for PRJNA714877
getting alias for PRJNA860564
getting alias for PRJNA251597
getting alias for PRJNA738168
getting alias for PRJNA940452
getting alias for PRJNA667267
getting alias for PRJNA822388
getting alias for PRJNA494693
getting alias for PRJNA369530
getting alias for PRJNA316982
getting alias for PRJEB22967
getting alias for PRJNA762916
getting alias for PRJNA639731
getting alias for PRJNA726555
getting alias for PRJNA438316
getting alias for PRJNA339000
getting alias for PRJNA429185
getting alias for PRJNA860957
getting alias for PRJNA620359
getting alias for PRJNA642871
getting alias for PRJNA913107
getting alias for PRJNA799378
getting alias for PRJEB2457
getting alias for PRJNA412889
getting alias for PRJNA495850
getting alias for PRJNA867337
getting alias for PRJNA909785
getting alias for PRJNA719729
getting alias for PRJNA806662
getting alias for PRJNA809747
getting alias for PRJEB58839
getting alias for PRJNA369751
getting alias for PRJNA433852
getting alias for PRJNA529202
getting alias for PRJNA1055983
getting alias for PRJNA507972
getting alias for PRJNA884701
getting alias for PRJNA540255
getting alias for PRJNA722928
getting alias for PRJNA525452
getting alias for PRJNA906465
getting alias for PRJNA525432
getting alias for PRJNA890568
getting alias for PRJNA658907
getting alias for PRJNA122227
getting alias for PRJNA493255
getting alias for PRJNA338073
getting alias for PRJNA314484
getting alias for PRJNA542790
getting alias for PRJNA391955
getting alias for PRJNA736615
getting alias for PRJNA875132
getting alias for PRJNA308073
getting alias for PRJNA788534
getting alias for PRJNA318516
getting alias for PRJNA978578
getting alias for PRJNA875917
getting alias for PRJNA780919
getting alias for PRJNA169134
getting alias for PRJNA1013049
getting alias for PRJNA1031962
getting alias for PRJNA317322
getting alias for PRJNA472997
getting alias for PRJNA170665
getting alias for PRJNA388398
getting alias for PRJNA230117
getting alias for PRJNA594413
getting alias for PRJNA472051
getting alias for PRJNA380344
getting alias for PRJNA336549
getting alias for PRJNA315864
getting alias for PRJNA724737
getting alias for PRJNA675765
getting alias for PRJNA903179
getting alias for PRJNA953419
getting alias for PRJNA317722
getting alias for PRJNA941921
getting alias for PRJNA601525
getting alias for PRJNA912137
getting alias for PRJNA638261
getting alias for PRJNA294786
getting alias for PRJNA477336
getting alias for PRJNA384979
getting alias for PRJNA1107978
getting alias for PRJNA525282
getting alias for PRJNA318748
getting alias for PRJNA998749
getting alias for PRJEB47885
getting alias for PRJNA843782
getting alias for PRJNA791363
getting alias for PRJNA839338
getting alias for PRJNA336060
getting alias for PRJNA472080
getting alias for PRJNA632508
getting alias for PRJNA647212
getting alias for PRJNA276444
getting alias for PRJNA232493
getting alias for PRJNA989599
getting alias for PRJNA641352
getting alias for PRJNA982119
getting alias for PRJNA481007
getting alias for PRJNA380922
getting alias for PRJNA238653
getting alias for PRJNA705455
getting alias for PRJNA358157
getting alias for PRJNA648424
getting alias for PRJNA528416
getting alias for PRJNA331045
getting alias for PRJNA607059
getting alias for PRJNA804535
getting alias for PRJNA803178
getting alias for PRJNA314692
getting alias for PRJNA421364
getting alias for PRJNA1118747
getting alias for PRJNA290078
getting alias for PRJNA295091
getting alias for PRJNA744433
getting alias for PRJNA925827
getting alias for PRJNA302003
getting alias for PRJNA527732
getting alias for PRJNA433874
getting alias for PRJNA708256
getting alias for PRJNA744559
getting alias for PRJNA1019271
getting alias for PRJNA453570
getting alias for PRJNA1036575
getting alias for PRJNA269310
getting alias for PRJNA270874
getting alias for PRJNA170237
getting alias for PRJNA433497
getting alias for PRJNA357201
getting alias for PRJNA389309
getting alias for PRJNA388207
getting alias for PRJNA553702
getting alias for PRJNA341576
getting alias for PRJNA385496
getting alias for PRJNA419538
getting alias for PRJNA556865
getting alias for PRJNA558807
getting alias for PRJNA604023
getting alias for PRJNA608263
getting alias for PRJNA311178
getting alias for PRJNA342005
getting alias for PRJNA766686
getting alias for PRJNA744409
getting alias for PRJNA511129
getting alias for PRJNA320883
getting alias for PRJNA399521
getting alias for PRJNA487079
getting alias for PRJNA566098
getting alias for PRJNA259631
getting alias for PRJNA757244
getting alias for PRJNA260855
getting alias for PRJNA787244
getting alias for PRJNA933934
getting alias for PRJNA649267
getting alias for PRJNA625345
getting alias for PRJNA451508
getting alias for PRJNA1036537
getting alias for PRJNA285810
getting alias for PRJNA926355
getting alias for PRJNA949668
getting alias for PRJNA737797
getting alias for PRJNA432917
getting alias for PRJNA749760
getting alias for PRJNA853318
getting alias for PRJNA321470
getting alias for PRJNA943236
getting alias for PRJNA844351
getting alias for PRJNA1075043
getting alias for PRJNA1001037
getting alias for PRJNA933653
getting alias for PRJNA564278
getting alias for PRJNA389285
getting alias for PRJNA577206
getting alias for PRJNA288172
getting alias for PRJNA565696
getting alias for PRJNA867717
getting alias for PRJNA1062790
getting alias for PRJNA813592
getting alias for PRJNA1037151
getting alias for PRJNA788402
getting alias for PRJNA954814
getting alias for PRJNA487051
getting alias for PRJNA881599
getting alias for PRJNA349052
getting alias for PRJNA880805
getting alias for PRJNA352201
getting alias for PRJNA649438
getting alias for PRJNA602727
getting alias for PRJNA352683
getting alias for PRJNA562704
getting alias for PRJNA399864
getting alias for PRJNA360334
getting alias for PRJNA919077
getting alias for PRJNA592361
getting alias for PRJNA879695
getting alias for PRJNA679226
getting alias for PRJNA701753
getting alias for PRJNA632653
getting alias for PRJNA167967
getting alias for PRJNA796611
getting alias for PRJNA967286
getting alias for PRJNA218537
getting alias for PRJNA630754
getting alias for PRJNA294094
getting alias for PRJNA486344
getting alias for PRJNA526668
getting alias for PRJNA925510
getting alias for PRJNA806646
getting alias for PRJNA655254
getting alias for PRJNA479861
getting alias for PRJNA448672
getting alias for PRJNA259680
getting alias for PRJNA750922
getting alias for PRJNA254505
getting alias for PRJNA639789
getting alias for PRJNA351855
getting alias for PRJNA317179
getting alias for PRJNA344695
getting alias for PRJNA736856
getting alias for PRJNA395465
getting alias for PRJNA716169
getting alias for PRJNA270886
getting alias for PRJNA861304
getting alias for PRJNA616378
getting alias for PRJNA479446
getting alias for PRJNA485348
getting alias for PRJNA776278
getting alias for PRJEB35753
getting alias for PRJNA555390
getting alias for PRJNA389675
getting alias for PRJNA1014466
getting alias for PRJNA772975
getting alias for PRJNA524194
getting alias for PRJNA480717
getting alias for PRJNA988452
getting alias for PRJNA613456
getting alias for PRJNA764192
getting alias for PRJNA362994
getting alias for PRJNA638540
getting alias for PRJNA342301
getting alias for PRJNA188503
getting alias for PRJNA235219
getting alias for PRJNA638678
getting alias for PRJNA322671
getting alias for PRJNA795495
getting alias for PRJNA1053328
getting alias for PRJNA407986
getting alias for PRJNA205864
getting alias for PRJNA485134
getting alias for PRJNA262970
getting alias for PRJNA151589
getting alias for PRJNA903916
getting alias for PRJNA523248
getting alias for PRJNA379206
getting alias for PRJNA1050300
getting alias for PRJEB12413
getting alias for PRJNA385669
getting alias for PRJNA169403
getting alias for PRJNA428511
getting alias for PRJNA781852
getting alias for PRJNA448580
getting alias for PRJNA839434
getting alias for PRJNA397064
getting alias for PRJNA691879
getting alias for PRJNA386485
getting alias for PRJNA551939
getting alias for PRJNA599395
getting alias for PRJNA384192
getting alias for PRJNA913128
getting alias for PRJNA721401
getting alias for PRJNA209644
getting alias for PRJNA566137
getting alias for PRJNA244662
getting alias for PRJNA146209
getting alias for PRJNA814690
getting alias for PRJNA639782
getting alias for PRJNA1093123
getting alias for PRJNA976655
getting alias for PRJNA169669
getting alias for PRJNA532420
getting alias for PRJNA925168
getting alias for PRJNA369328
getting alias for PRJNA511488
getting alias for PRJNA244365
getting alias for PRJNA588415
getting alias for PRJNA254703
getting alias for PRJNA285758
getting alias for PRJNA196838
getting alias for PRJNA678733
getting alias for PRJNA1011298
getting alias for PRJNA1043393
getting alias for PRJNA687751
getting alias for PRJNA499084
getting alias for PRJNA153225
getting alias for PRJNA270526
getting alias for PRJNA1092698
getting alias for PRJNA296039
getting alias for PRJNA824442
getting alias for PRJNA429126
getting alias for PRJNA381131
getting alias for PRJNA360412
getting alias for PRJNA362641
getting alias for PRJNA321410
getting alias for PRJNA428403
getting alias for PRJNA225010
getting alias for PRJNA643282
getting alias for PRJNA488719
getting alias for PRJNA79729
getting alias for PRJNA131113
getting alias for PRJNA534210
getting alias for PRJNA310222
getting alias for PRJNA896232
getting alias for PRJNA505666
getting alias for PRJNA374856
getting alias for PRJNA726641
getting alias for PRJNA996130
getting alias for PRJNA434810
getting alias for PRJNA209324
getting alias for PRJNA533237
getting alias for PRJNA757754
getting alias for PRJNA273631
getting alias for PRJNA514309
getting alias for PRJNA508784
getting alias for PRJNA380201
getting alias for PRJNA548091
getting alias for PRJNA591124
getting alias for PRJNA419486
getting alias for PRJNA379933
getting alias for PRJNA286795
getting alias for PRJNA149369
getting alias for PRJNA957136
getting alias for PRJNA352042
getting alias for PRJNA336041
getting alias for PRJNA637085
getting alias for PRJNA316811
getting alias for PRJNA898333
getting alias for PRJNA394842
getting alias for PRJNA699482
getting alias for PRJNA510312
getting alias for PRJNA378528
getting alias for PRJNA355875
getting alias for PRJNA785252
getting alias for PRJNA354330
getting alias for PRJNA722862
getting alias for PRJNA387926

In [6]:
mapped_df

0,->,PRJNA852208,10533,SRP383392
1,->,PRJEB15671,8315,ERP017503
2,->,PRJEB25079,6986,ERP106963
3,->,PRJNA945404,6909,SRP427656
4,->,PRJEB19252,4882,ERP021242
:,,...,...,...
821,->,PRJNA319661,22,SRP073942
822,->,PRJNA718567,18,SRP312746
823,->,PRJNA117657,18,SRP002566
824,->,PRJNA744531,16,SRP327393
825,->,PRJNA79813,15,SRP004053

In [7]:
open System.Text.RegularExpressions

let dee2DumpUrl org acc =
    let html =
        http {
            GET $"https://dee2.io/cgi-bin/search2.sh?org={org}&accessionsearch={acc}"
        }
        |> Request.send
        |> Response.toText
    if html.Contains "No results found" then
        None
    else
        let m = Regex.Match(html, @"href=(https?://[^\s""'>]+\.zip)")
        if m.Success then Some m.Groups.[1].Value else None

dee2DumpUrl "athaliana" "SRP427656"

In [8]:
let with_dee2_urls =
    mapped_df
    |> fun f ->
        let dee2_col =
            f
            |> Frame.mapRows (fun rk os ->
                let acc = os.GetAs<string>("Alias")
                printfn "getting dee2 url for %s" acc
                dee2DumpUrl "athaliana" acc
                |> Option.defaultValue ""
            )
        let f' = f |> Frame.addCol "dee2_url" dee2_col

        let has_dee_col =
            f'
            |> Frame.mapRows (fun rk os ->
                let acc = os.GetAs<string>("dee2_url")
                if acc = "" then false else true
            )
        f'
        |> Frame.addCol "has_dee2" has_dee_col

getting dee2 url for SRP383392
getting dee2 url for ERP017503
getting dee2 url for ERP106963
getting dee2 url for SRP427656
getting dee2 url for ERP021242
getting dee2 url for SRP035593
getting dee2 url for SRP360684
getting dee2 url for SRP097877
getting dee2 url for SRP095347
getting dee2 url for SRP285902
getting dee2 url for SRP150217
getting dee2 url for SRP364447
getting dee2 url for SRP446862
getting dee2 url for SRP414670
getting dee2 url for SRP168223
getting dee2 url for SRP155742
getting dee2 url for SRP066214
getting dee2 url for SRP340951
getting dee2 url for SRP179923
getting dee2 url for SRP252208
getting dee2 url for SRP266864
getting dee2 url for SRP376838
getting dee2 url for SRP282567
getting dee2 url for SRP407150
getting dee2 url for SRP345289
getting dee2 url for SRP103736
getting dee2 url for SRP254043
getting dee2 url for SRP031910
getting dee2 url for SRP212174
getting dee2 url for SRP101641
getting dee2 url for SRP300093
getting dee2 url for SRP318562
getting dee2 url for SRP393237
getting dee2 url for SRP199974
getting dee2 url for SRP352332
getting dee2 url for SRP301115
getting dee2 url for SRP125388
getting dee2 url for SRP268298
getting dee2 url for SRP128933
getting dee2 url for SRP154321
getting dee2 url for SRP320382
getting dee2 url for SRP459156
getting dee2 url for SRP394711
getting dee2 url for SRP323822
getting dee2 url for SRP162754
getting dee2 url for SRP424504
getting dee2 url for SRP222258
getting dee2 url for SRP199288
getting dee2 url for SRP151817
getting dee2 url for SRP260029
getting dee2 url for SRP223758
getting dee2 url for SRP258701
getting dee2 url for SRP256503
getting dee2 url for SRP168517
getting dee2 url for SRP252735
getting dee2 url for SRP069988
getting dee2 url for SRP169564
getting dee2 url for SRP151348
getting dee2 url for SRP327627
getting dee2 url for SRP059724
getting dee2 url for SRP200108
getting dee2 url for SRP229078
getting dee2 url for SRP415041
getting dee2 url for SRP073485
getting dee2 url for SRP303532
getting dee2 url for SRP267137
getting dee2 url for SRP499774
getting dee2 url for SRP218715
getting dee2 url for SRP265579
getting dee2 url for SRP150839
getting dee2 url for SRP463096
getting dee2 url for SRP176448
getting dee2 url for SRP187842
getting dee2 url for SRP201971
getting dee2 url for SRP193460
getting dee2 url for SRP254970
getting dee2 url for SRP274617
getting dee2 url for SRP244461
getting dee2 url for SRP308812
getting dee2 url for SRP352133
getting dee2 url for SRP289447
getting dee2 url for SRP425303
getting dee2 url for SRP253380
getting dee2 url for SRP033660
getting dee2 url for SRP292364
getting dee2 url for SRP172401
getting dee2 url for SRP447605
getting dee2 url for SRP254177
getting dee2 url for SRP242315
getting dee2 url for SRP189599
getting dee2 url for ERP116333
getting dee2 url for SRP072503
getting dee2 url for SRP285240
getting dee2 url for SRP394299
getting dee2 url for SRP281951
getting dee2 url for SRP295378
getting dee2 url for SRP279501
getting dee2 url for SRP428801
getting dee2 url for SRP030646
getting dee2 url for SRP199446
getting dee2 url for SRP360394
getting dee2 url for SRP122518
getting dee2 url for SRP100933
getting dee2 url for SRP013427
getting dee2 url for SRP440333
getting dee2 url for SRP065994
getting dee2 url for SRP462736
getting dee2 url for SRP311233
getting dee2 url for SRP055902
getting dee2 url for SRP413216
getting dee2 url for SRP251062
getting dee2 url for SRP267870
getting dee2 url for SRP212094
getting dee2 url for SRP441917
getting dee2 url for SRP150864
getting dee2 url for SRP311462
getting dee2 url for SRP151058
getting dee2 url for SRP268265
getting dee2 url for SRP423048
getting dee2 url for SRP174391
getting dee2 url for SRP312223
getting dee2 url for SRP097638
getting dee2 url for SRP305304
getting dee2 url for SRP311646
getting dee2 url for SRP311856
getting dee2 url for SRP280005
getting dee2 url for SRP436704
getting dee2 url for SRP269194
getting dee2 url for SRP357889
getting dee2 url for SRP365283
getting dee2 url for SRP395920
getting dee2 url for SRP014002
getting dee2 url for SRP103817
getting dee2 url for SRP127334
getting dee2 url for SRP404043
getting dee2 url for SRP361833
getting dee2 url for SRP041593
getting dee2 url for SRP339340
getting dee2 url for SRP136269
getting dee2 url for SRP098589
getting dee2 url for ERP119709
getting dee2 url for SRP316571
getting dee2 url for SRP374808
getting dee2 url for SRP384635
getting dee2 url for SRP074436
getting dee2 url for SRP359805
getting dee2 url for SRP071076
getting dee2 url for SRP422296
getting dee2 url for SRP218235
getting dee2 url for SRP149067
getting dee2 url for SRP028132
getting dee2 url for SRP375081
getting dee2 url for SRP338075
getting dee2 url for SRP117360
getting dee2 url for SRP201460
getting dee2 url for SRP132865
getting dee2 url for SRP333294
getting dee2 url for SRP311927
getting dee2 url for SRP042618
getting dee2 url for SRP371881
getting dee2 url for SRP458867
getting dee2 url for SRP128550
getting dee2 url for SRP391092
getting dee2 url for SRP112501
getting dee2 url for SRP132472
getting dee2 url for SRP021196
getting dee2 url for SRP214325
getting dee2 url for SRP048829
getting dee2 url for SRP253504
getting dee2 url for SRP314217
getting dee2 url for SRP237550
getting dee2 url for SRP056594
getting dee2 url for SRP095841
getting dee2 url for SRP426253
getting dee2 url for SRP188654
getting dee2 url for SRP307159
getting dee2 url for SRP314501
getting dee2 url for SRP199045
getting dee2 url for SRP177951
getting dee2 url for SRP105272
getting dee2 url for SRP029215
getting dee2 url for SRP297920
getting dee2 url for SRP065557
getting dee2 url for SRP191092
getting dee2 url for SRP351674
getting dee2 url for SRP178122
getting dee2 url for SRP408086
getting dee2 url for SRP421663
getting dee2 url for SRP376989
getting dee2 url for SRP440261
getting dee2 url for SRP242107
getting dee2 url for SRP234996
getting dee2 url for SRP299921
getting dee2 url for SRP161929
getting dee2 url for SRP255966
getting dee2 url for SRP464952
getting dee2 url for SRP134213
getting dee2 url for SRP352479
getting dee2 url for SRP127502
getting dee2 url for SRP214607
getting dee2 url for SRP330827
getting dee2 url for SRP070187
getting dee2 url for SRP315390
getting dee2 url for SRP294483
getting dee2 url for SRP251005
getting dee2 url for SRP133385
getting dee2 url for SRP331164
getting dee2 url for SRP328160
getting dee2 url for SRP430513
getting dee2 url for SRP338573
getting dee2 url for SRP408456
getting dee2 url for SRP315418
getting dee2 url for SRP323376
getting dee2 url for SRP415054
getting dee2 url for SRP372716
getting dee2 url for SRP379557
getting dee2 url for SRP294481
getting dee2 url for SRP259350
getting dee2 url for ERP023139
getting dee2 url for SRP056488
getting dee2 url for SRP139506
getting dee2 url for SRP185774
getting dee2 url for SRP306737
getting dee2 url for SRP439248
getting dee2 url for SRP092349
getting dee2 url for SRP189805
getting dee2 url for SRP099107
getting dee2 url for SRP331699
getting dee2 url for SRP219922
getting dee2 url for SRP312149
getting dee2 url for SRP320161
getting dee2 url for SRP121654
getting dee2 url for SRP288586
getting dee2 url for SRP272284
getting dee2 url for SRP386435
getting dee2 url for SRP286187
getting dee2 url for SRP053347
getting dee2 url for SRP510880
getting dee2 url for SRP051531
getting dee2 url for SRP066358
getting dee2 url for SRP370523
getting dee2 url for SRP127815
getting dee2 url for SRP377972
getting dee2 url for SRP491353
getting dee2 url for SRP057846
getting dee2 url for SRP034154
getting dee2 url for SRP362135
getting dee2 url for SRP157330
getting dee2 url for SRP199048
getting dee2 url for SRP154459
getting dee2 url for ERP122873
getting dee2 url for SRP345540
getting dee2 url for SRP075927
getting dee2 url for SRP427827
getting dee2 url for SRP160880
getting dee2 url for SRP271551
getting dee2 url for SRP105182
getting dee2 url for SRP401789
getting dee2 url for SRP200395
getting dee2 url for SRP109012
getting dee2 url for SRP149670
getting dee2 url for SRP076998
getting dee2 url for SRP315222
getting dee2 url for SRP234703
getting dee2 url for SRP441643
getting dee2 url for SRP098817
getting dee2 url for SRP156229
getting dee2 url for SRP237791
getting dee2 url for SRP301936
getting dee2 url for SRP108277
getting dee2 url for SRP297574
getting dee2 url for SRP156399
getting dee2 url for SRP228588
getting dee2 url for SRP274014
getting dee2 url for SRP361795
getting dee2 url for SRP360141
getting dee2 url for SRP470122
getting dee2 url for SRP113516
getting dee2 url for SRP378694
getting dee2 url for SRP120000
getting dee2 url for SRP309511
getting dee2 url for SRP139782
getting dee2 url for SRP372383
getting dee2 url for SRP076861
getting dee2 url for SRP068145
getting dee2 url for SRP161785
getting dee2 url for SRP059744
getting dee2 url for SRP060240
getting dee2 url for SRP075884
getting dee2 url for SRP347084
getting dee2 url for SRP421875
getting dee2 url for SRP126290
getting dee2 url for SRP174236
getting dee2 url for SRP233165
getting dee2 url for SRP145580
getting dee2 url for SRP250665
getting dee2 url for SRP336673
getting dee2 url for SRP241907
getting dee2 url for SRP251246
getting dee2 url for SRP199385
getting dee2 url for SRP440722
getting dee2 url for SRP118853
getting dee2 url for SRP238841
getting dee2 url for SRP063314
getting dee2 url for SRP402463
getting dee2 url for SRP219435
getting dee2 url for SRP102243
getting dee2 url for SRP191553
getting dee2 url for SRP192391
getting dee2 url for SRP010063
getting dee2 url for SRP474470
getting dee2 url for SRP323231
getting dee2 url for SRP037581
getting dee2 url for SRP187156
getting dee2 url for SRP136326
getting dee2 url for SRP386399
getting dee2 url for SRP200994
getting dee2 url for SRP406814
getting dee2 url for SRP268150
getting dee2 url for SRP310860
getting dee2 url for SRP387278
getting dee2 url for SRP042942
getting dee2 url for SRP324166
getting dee2 url for SRP425357
getting dee2 url for SRP286312
getting dee2 url for SRP366979
getting dee2 url for SRP163443
getting dee2 url for SRP098693
getting dee2 url for SRP072685
getting dee2 url for ERP104697
getting dee2 url for SRP336880
getting dee2 url for SRP267488
getting dee2 url for SRP318031
getting dee2 url for SRP135688
getting dee2 url for SRP082176
getting dee2 url for SRP128509
getting dee2 url for SRP387808
getting dee2 url for SRP254767
getting dee2 url for SRP269252
getting dee2 url for SRP413428
getting dee2 url for SRP356192
getting dee2 url for ERP000565;ERP000565
getting dee2 url for SRP119267
getting dee2 url for SRP165229
getting dee2 url for SRP390531
getting dee2 url for SRP411860
getting dee2 url for SRP313445
getting dee2 url for SRP359646
getting dee2 url for SRP361197
getting dee2 url for ERP143913
getting dee2 url for SRP098793
getting dee2 url for SRP132710
getting dee2 url for SRP189482
getting dee2 url for SRP479745
getting dee2 url for SRP172049
getting dee2 url for SRP399863
getting dee2 url for SRP194124
getting dee2 url for SRP315323
getting dee2 url for SRP187477
getting dee2 url for SRP410391
getting dee2 url for SRP187455
getting dee2 url for SRP402633
getting dee2 url for SRP278587
getting dee2 url for SRP001589
getting dee2 url for SRP162679
getting dee2 url for SRP081052
getting dee2 url for SRP071212
getting dee2 url for SRP198341
getting dee2 url for SRP110536
getting dee2 url for SRP323534
getting dee2 url for SRP394932
getting dee2 url for SRP068137
getting dee2 url for SRP350800
getting dee2 url for SRP073326
getting dee2 url for SRP440710
getting dee2 url for SRP399524
getting dee2 url for SRP346400
getting dee2 url for SRP013873
getting dee2 url for SRP458621
getting dee2 url for SRP468279
getting dee2 url for SRP072879
getting dee2 url for SRP148906
getting dee2 url for SRP014189
getting dee2 url for SRP108255
getting dee2 url for SRP033370
getting dee2 url for SRP235374
getting dee2 url for SRP148438
getting dee2 url for SRP102435
getting dee2 url for SRP080945
getting dee2 url for SRP072125
getting dee2 url for SRP316120
getting dee2 url for SRP291935
getting dee2 url for SRP408638
getting dee2 url for SRP431509
getting dee2 url for SRP073021
getting dee2 url for SRP426021
getting dee2 url for SRP242108
getting dee2 url for SRP413007
getting dee2 url for SRP266555
getting dee2 url for SRP063352
getting dee2 url for SRP151039
getting dee2 url for SRP105773
getting dee2 url for SRP505788
getting dee2 url for SRP187356
getting dee2 url for SRP073430
getting dee2 url for SRP451592
getting dee2 url for ERP132204
getting dee2 url for SRP377671
getting dee2 url for SRP351965
getting dee2 url for SRP375869
getting dee2 url for SRP080772
getting dee2 url for SRP148468
getting dee2 url for SRP261411
getting dee2 url for SRP272493
getting dee2 url for SRP055503
getting dee2 url for SRP034702
getting dee2 url for SRP446819
getting dee2 url for SRP268461
getting dee2 url for SRP442316
getting dee2 url for SRP153372
getting dee2 url for SRP102698
getting dee2 url for SRP038129
getting dee2 url for SRP308553
getting dee2 url for SRP095390
getting dee2 url for SRP273472
getting dee2 url for SRP189046
getting dee2 url for SRP079522
getting dee2 url for SRP249704
getting dee2 url for SRP358942
getting dee2 url for SRP358094
getting dee2 url for SRP071310
getting dee2 url for SRP126292
getting dee2 url for SRP511048
getting dee2 url for SRP061231
getting dee2 url for SRP063471
getting dee2 url for SRP327331
getting dee2 url for SRP418417
getting dee2 url for SRP066116
getting dee2 url for SRP188687
getting dee2 url for SRP132727
getting dee2 url for SRP309953
getting dee2 url for SRP327413
getting dee2 url for SRP461945
getting dee2 url for SRP142625
getting dee2 url for SRP470539
getting dee2 url for SRP050570
getting dee2 url for SRP051392
getting dee2 url for SRP014178
getting dee2 url for SRP132470
getting dee2 url for SRP095010
getting dee2 url for SRP108633
getting dee2 url for SRP108133
getting dee2 url for SRP214076
getting dee2 url for SRP084243
getting dee2 url for SRP106473
getting dee2 url for SRP125498
getting dee2 url for SRP216517
getting dee2 url for SRP218253
getting dee2 url for SRP246179
getting dee2 url for SRP250465
getting dee2 url for SRP069764
getting dee2 url for SRP086708
getting dee2 url for SRP338944
getting dee2 url for SRP327317
getting dee2 url for SRP174146
getting dee2 url for SRP074486
getting dee2 url for SRP115958
getting dee2 url for SRP158529
getting dee2 url for SRP222257
getting dee2 url for SRP045820
getting dee2 url for SRP333850
getting dee2 url for SRP047055
getting dee2 url for SRP349824
getting dee2 url for SRP422064
getting dee2 url for SRP273996
getting dee2 url for SRP256398
getting dee2 url for SRP142348
getting dee2 url for SRP470537
getting dee2 url for SRP059041
getting dee2 url for SRP418630
getting dee2 url for SRP429792
getting dee2 url for SRP324131
getting dee2 url for SRP132174
getting dee2 url for SRP329913
getting dee2 url for SRP383790
getting dee2 url for SRP074999
getting dee2 url for SRP426622
getting dee2 url for SRP378006
getting dee2 url for SRP489101
getting dee2 url for SRP452634
getting dee2 url for SRP421887
getting dee2 url for SRP220660
getting dee2 url for SRP108611
getting dee2 url for SRP226805
getting dee2 url for SRP059890
getting dee2 url for SRP221724
getting dee2 url for SRP390739
getting dee2 url for SRP482746
getting dee2 url for SRP362933
getting dee2 url for SRP470906
getting dee2 url for SRP350493
getting dee2 url for SRP432248
getting dee2 url for SRP158513
getting dee2 url for SRP397806
getting dee2 url for SRP091720
getting dee2 url for SRP397557
getting dee2 url for SRP092447
getting dee2 url for SRP274096
getting dee2 url for SRP244078
getting dee2 url for SRP092754
getting dee2 url for SRP219510
getting dee2 url for SRP116095
getting dee2 url for SRP096152
getting dee2 url for SRP416223
getting dee2 url for SRP233666
getting dee2 url for SRP396754
getting dee2 url for SRP293071
getting dee2 url for SRP306303
getting dee2 url for SRP261520
getting dee2 url for SRP013533
getting dee2 url for SRP354761
getting dee2 url for SRP435965
getting dee2 url for SRP029707
getting dee2 url for SRP260311
getting dee2 url for SRP062911
getting dee2 url for SRP158137
getting dee2 url for SRP188198
getting dee2 url for SRP418301
getting dee2 url for SRP359627
getting dee2 url for SRP275850
getting dee2 url for SRP152313
getting dee2 url for SRP137051
getting dee2 url for SRP045843
getting dee2 url for SRP330536
getting dee2 url for SRP044116
getting dee2 url for SRP267518
getting dee2 url for SRP092341
getting dee2 url for SRP072774
getting dee2 url for SRP090526
getting dee2 url for SRP323708
getting dee2 url for SRP113410
getting dee2 url for SRP311577
getting dee2 url for SRP051400
getting dee2 url for SRP387625
getting dee2 url for SRP254665
getting dee2 url for SRP151891
getting dee2 url for SRP156937
getting dee2 url for SRP343767
getting dee2 url for ERP118861
getting dee2 url for SRP215328
getting dee2 url for SRP108830
getting dee2 url for SRP459352
getting dee2 url for SRP342274
getting dee2 url for SRP186822
getting dee2 url for SRP153116
getting dee2 url for SRP446296
getting dee2 url for SRP253340
getting dee2 url for SRP337613
getting dee2 url for SRP097657
getting dee2 url for SRP266735
getting dee2 url for SRP087624
getting dee2 url for SRP018404
getting dee2 url for SRP035440
getting dee2 url for SRP266840
getting dee2 url for SRP075658
getting dee2 url for SRP354000
getting dee2 url for SRP478327
getting dee2 url for SRP118154
getting dee2 url for SRP023272
getting dee2 url for SRP156748
getting dee2 url for SRP048616
getting dee2 url for SRP010481
getting dee2 url for SRP409012
getting dee2 url for SRP186316
getting dee2 url for SRP101909
getting dee2 url for SRP476750
getting dee2 url for ERP013888
getting dee2 url for SRP106557
getting dee2 url for SRP013916
getting dee2 url for SRP128055
getting dee2 url for SRP346907
getting dee2 url for SRP137005
getting dee2 url for SRP375971
getting dee2 url for SRP114786
getting dee2 url for SRP301597
getting dee2 url for SRP106994
getting dee2 url for SRP212662
getting dee2 url for SRP239820
getting dee2 url for SRP105190
getting dee2 url for SRP413446
getting dee2 url for SRP314497
getting dee2 url for SRP026334
getting dee2 url for SRP222301
getting dee2 url for SRP041185
getting dee2 url for SRP007581
getting dee2 url for SRP363467
getting dee2 url for SRP267522
getting dee2 url for SRP498485
getting dee2 url for SRP439789
getting dee2 url for SRP013996
getting dee2 url for SRP192092
getting dee2 url for SRP418140
getting dee2 url for SRP098619
getting dee2 url for SRP174262
getting dee2 url for SRP041113
getting dee2 url for SRP229345
getting dee2 url for SRP044142
getting dee2 url for SRP059030
getting dee2 url for SRP020950
getting dee2 url for SRP292754
getting dee2 url for SRP457858
getting dee2 url for SRP473153
getting dee2 url for SRP299535
getting dee2 url for SRP167149
getting dee2 url for SRP011409
getting dee2 url for SRP051214
getting dee2 url for SRP498287
getting dee2 url for SRP063893
getting dee2 url for SRP368024
getting dee2 url for SRP128495
getting dee2 url for SRP102803
getting dee2 url for SRP096188
getting dee2 url for SRP097224
getting dee2 url for SRP074890
getting dee2 url for SRP127991
getting dee2 url for SRP032274
getting dee2 url for SRP269433
getting dee2 url for SRP159234
getting dee2 url for SRP003234
getting dee2 url for SRP003413
getting dee2 url for SRP193429
getting dee2 url for SRP069072
getting dee2 url for SRP405526
getting dee2 url for SRP168763
getting dee2 url for SRP099840
getting dee2 url for SRP318086
getting dee2 url for SRP450135
getting dee2 url for SRP133210
getting dee2 url for SRP026260
getting dee2 url for SRP192828
getting dee2 url for SRP334109
getting dee2 url for SRP052825
getting dee2 url for SRP178230
getting dee2 url for SRP172777

In [12]:
with_dee2_urls.SaveCsv("./ProjectsWithTotalAttributesWithDee2Urls.csv", includeRowKeys=false)

In [27]:
let candidates = 
    with_dee2_urls
    |> Frame.filterRows (fun rk os ->
        os.GetAs<bool>("has_dee2")
    )
    |> Frame.mapRows (fun rk os ->
        os.GetAs<string>("Project_Accession"), os.GetAs<int>("Total_Attributes")
    )
    |> Series.values
    |> Seq.sortByDescending (fun (_, total) -> total)
    |> Seq.take 39
    |> Array.ofSeq

candidates

In [ ]:
// --- Create one empty GitLab repo per candidate accession ---
open FsHttp

let gitlabHost = "https://git.nfdi4plants.org"   // TODO: your instance, no trailing slash
let groupId    = 238457374                                // TODO: numeric group ID (Group -> Settings -> General)
let token      = "NAH BRO"  // PAT with `api` scope

let createRepo (acc: string) =
    let payload =
        sprintf "{\"name\":\"%s\",\"path\":\"%s\",\"namespace_id\":%d,\"visibility\":\"private\"}" acc acc groupId
    let resp =
        http {
            POST $"{gitlabHost}/api/v4/projects"
            header "PRIVATE-TOKEN" token
            body
            json payload
        }
        |> Request.send
    let status = int resp.statusCode
    if status = 201 then
        printfn "created %s" acc
    else
        printfn "FAILED %s -> %d: %s" acc status (resp |> Response.toText)
    acc, status

let results =
    candidates
    |> Array.map (fun (acc, _) -> createRepo acc)

created PRJEB25079
created PRJNA945404
created PRJNA808745
created PRJNA368916
created PRJNA358059
created PRJNA666631
created PRJNA475542
created PRJNA989636
created PRJNA915364
created PRJNA504621
created PRJNA483458
created PRJNA302221
created PRJNA515610
created PRJNA611770
created PRJNA638728
created PRJNA841954
created PRJNA663790
created PRJNA779072
created PRJNA382136
created PRJNA224705
created PRJNA551415
created PRJNA378644
created PRJNA727531
created PRJNA871888
created PRJNA691022
created PRJNA419306
created PRJNA641096
created PRJNA429659
created PRJNA481720
created PRJNA730903
created PRJNA1014093
created PRJNA737113
created PRJNA938512
created PRJNA566089
created PRJNA544417
created PRJNA478998
created PRJNA630258
created PRJNA575019
created PRJNA628644

In [29]:
// --- Web URLs for the candidate repos ---
open System.Text.Json

// fetch the target group's web URL once
let groupWebUrl =
    http {
        GET $"{gitlabHost}/api/v4/groups/{groupId}"
        header "PRIVATE-TOKEN" token
    }
    |> Request.send
    |> Response.toText
    |> JsonDocument.Parse
    |> fun d -> d.RootElement.GetProperty("web_url").GetString()

// path was set to the accession at creation, so URL = group/web_url + "/" + accession
let repoUrls =
    candidates
    |> Array.map (fun (acc, _) -> acc, $"{groupWebUrl}/{acc}")

repoUrls